"""Automated Map of Content (MOC) and Living Wiki Index Synthesizer (Python edition).

Provides idempotent, non-destructive wiki synthesis, taxonomy tree grouping,
PageRank-weighted hub ordering, and orphan detection.
"""

from __future__ import annotations
from dataclasses import dataclass
import os
from pathlib import Path
from typing import Dict, List, Optional, Tuple

from atlaswiki.ast import ParsedDocument
from atlaswiki.graph import KnowledgeGraph
from atlaswiki.parser import MarkdownParser

SYNTHESIS_BEGIN = "<!-- ATLASWIKI:BEGIN_SYNTHESIS -->"
SYNTHESIS_END = "<!-- ATLASWIKI:END_SYNTHESIS -->"


@dataclass
class TopicMocInfo:
    topic: str
    file_path: str
    note_count: int
    tags_covered: List[str]


@dataclass
class MocReport:
    topic: str
    file_path: str
    note_count: int
    hub_notes: List[str]
    dry_run: bool
    content: Optional[str] = None


@dataclass
class LivingWikiReport:
    index_path: str
    orphans_path: str
    topic_mocs: List[TopicMocInfo]
    total_notes: int
    total_orphans: int
    dry_run: bool


def update_synthesis_content(
    existing: str,
    synthesized_body: str,
    default_header: Optional[str] = None,
) -> str:
    """Idempotently replaces or inserts the synthesized block into existing note content.

    Preserves any user edits outside `<!-- ATLASWIKI:BEGIN_SYNTHESIS -->` and `<!-- ATLASWIKI:END_SYNTHESIS -->`.
    """
    body = synthesized_body.strip()
    block = f"{SYNTHESIS_BEGIN}\n{body}\n{SYNTHESIS_END}"

    begin_idx = existing.find(SYNTHESIS_BEGIN)
    if begin_idx != -1:
        end_rel = existing[begin_idx:].find(SYNTHESIS_END)
        if end_rel != -1:
            end_idx = begin_idx + end_rel + len(SYNTHESIS_END)
            before = existing[:begin_idx]
            after = existing[end_idx:]
            return f"{before}{block}{after}"

    # No existing block found
    trimmed = existing.strip()
    if not trimmed:
        header = default_header or ""
        if header:
            return f"{header}\n\n{block}\n"
        return f"{block}\n"

    return f"{trimmed}\n\n{block}\n"


class MocSynthesizer:
    """Generates and maintains Maps of Content (MOC) and living vault index."""

    def __init__(self, vault_root: str | Path) -> None:
        self.vault_root = Path(vault_root).resolve()
        self.parser = MarkdownParser()

    def load_vault(self) -> Tuple[List[ParsedDocument], KnowledgeGraph]:
        docs: List[ParsedDocument] = []
        for root, dirs, files in os.walk(self.vault_root):
            # Ignore hidden dirs
            dirs[:] = [d for d in dirs if not d.startswith(".") and d != "node_modules"]
            for f in files:
                if f.endswith(".md"):
                    full_p = Path(root) / f
                    try:
                        content = full_p.read_text(encoding="utf-8", errors="replace")
                        doc = self.parser.parse_file(str(full_p), content)
                        docs.append(doc)
                    except Exception:
                        pass
        kg = KnowledgeGraph.from_documents(docs)
        kg.compute_pagerank()
        return docs, kg

    def generate_living_index(self, dry_run: bool = False) -> LivingWikiReport:
        docs, kg = self.load_vault()
        orphans = kg.get_orphans()

        # Group by first tag or category
        topics: Dict[str, List[ParsedDocument]] = {}
        for doc in docs:
            t = doc.tags[0].name.split("/")[0] if doc.tags else "General"
            topics.setdefault(t, []).append(doc)

        # Build index body
        lines = [
            "# Vault Knowledge Atlas",
            "",
            "Automated living knowledge index generated by **AtlasWiki**.",
            "",
            f"**Total Vault Notes:** {len(docs)}  ",
            f"**Orphan Notes:** {len(orphans)}  ",
            f"**Topic Areas:** {len(topics)}  ",
            "",
            "---",
            "",
            "## Knowledge Domains",
            "",
        ]

        topic_infos: List[TopicMocInfo] = []
        for topic, topic_docs in sorted(
            topics.items(), key=lambda x: len(x[1]), reverse=True
        ):
            topic_docs.sort(key=lambda d: kg.get_pagerank(d.title), reverse=True)
            top_hubs = [f"[[{d.title}]]" for d in topic_docs[:5]]
            lines.append(f"### {topic.capitalize()} ({len(topic_docs)} notes)")
            lines.append(f"Top Hubs: {', '.join(top_hubs) if top_hubs else '_none_'}")
            for d in topic_docs[:10]:
                pr = kg.get_pagerank(d.title)
                lines.append(f"- [[{d.title}]] `(PageRank: {pr:.4f})`")
            if len(topic_docs) > 10:
                lines.append(f"- _...and {len(topic_docs) - 10} more notes_")
            lines.append("")

            topic_infos.append(
                TopicMocInfo(
                    topic=topic,
                    file_path=str(self.vault_root / f"MOC_{topic}.md"),
                    note_count=len(topic_docs),
                    tags_covered=[topic],
                )
            )

        index_file = self.vault_root / "Index.md"
        orphans_file = self.vault_root / "Orphans.md"

        new_index_content = "\n".join(lines)
        if not dry_run:
            existing = (
                index_file.read_text(encoding="utf-8") if index_file.exists() else ""
            )
            final_content = update_synthesis_content(
                existing, new_index_content, default_header="# Vault Index"
            )
            index_file.write_text(final_content, encoding="utf-8")

            # Write orphans
            orphan_lines = [
                "# Orphan Notes",
                "",
                "These notes have 0 incoming and 0 outgoing links:",
                "",
            ]
            for o in sorted(orphans):
                orphan_lines.append(f"- [[{o}]]")
            orphan_lines.append("")
            orphan_body = "\n".join(orphan_lines)
            existing_o = (
                orphans_file.read_text(encoding="utf-8")
                if orphans_file.exists()
                else ""
            )
            final_orphans = update_synthesis_content(
                existing_o, orphan_body, default_header="# Orphan Notes"
            )
            orphans_file.write_text(final_orphans, encoding="utf-8")

        return LivingWikiReport(
            index_path=str(index_file),
            orphans_path=str(orphans_file),
            topic_mocs=topic_infos,
            total_notes=len(docs),
            total_orphans=len(orphans),
            dry_run=dry_run,
        )

    def generate_moc(
        self, topic: Optional[str] = None, dry_run: bool = False
    ) -> List[MocReport]:
        docs, kg = self.load_vault()
        reports: List[MocReport] = []

        topics_map: Dict[str, List[ParsedDocument]] = {}
        for doc in docs:
            tag_names = [t.name.lower() for t in doc.tags]
            if topic:
                t_lower = topic.lower()
                if (
                    any(t_lower in tn for tn in tag_names)
                    or t_lower in doc.title.lower()
                ):
                    topics_map.setdefault(topic, []).append(doc)
            else:
                for t in tag_names:
                    main_t = t.split("/")[0]
                    topics_map.setdefault(main_t, []).append(doc)

        for top_name, matched_docs in topics_map.items():
            matched_docs.sort(key=lambda d: kg.get_pagerank(d.title), reverse=True)
            hub_names = [d.title for d in matched_docs[:5]]

            body_lines = [
                f"# Map of Content: {top_name.capitalize()}",
                "",
                f"Curated index of **{len(matched_docs)}** notes related to `{top_name}`.",
                "",
                "### Central Hubs",
            ]
            for h in hub_names:
                body_lines.append(f"- [[{h}]]")

            body_lines.extend(["", "### All Notes in Topic"])
            for d in matched_docs:
                body_lines.append(f"- [[{d.title}]]")

            moc_body = "\n".join(body_lines)
            out_file = self.vault_root / f"MOC_{top_name.capitalize()}.md"

            if not dry_run:
                existing = (
                    out_file.read_text(encoding="utf-8") if out_file.exists() else ""
                )
                final_text = update_synthesis_content(
                    existing, moc_body, default_header=f"# MOC {top_name.capitalize()}"
                )
                out_file.write_text(final_text, encoding="utf-8")

            reports.append(
                MocReport(
                    topic=top_name,
                    file_path=str(out_file),
                    note_count=len(matched_docs),
                    hub_notes=hub_names,
                    dry_run=dry_run,
                    content=moc_body if dry_run else None,
                )
            )

        return reports
